//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace korona1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class place_user
    {
        public int placeID { get; set; }
        public int UuserID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Place Place { get; set; }
        public virtual User User { get; set; }
    }
}
